=== joseluissdb/mi-proyecto/XML/XML/receta.xml/andres/receta.dtd
<!ELEMENT cocina (receta*)>
<!ELEMENT receta (ID,nombre,ingredientes,proceso)>
<!ATTLIST receta 
vegano CDATA #REQUIRED 
noGluten CDATA #REQUIRED
noLactosa CDATA #REQUIRED 
dificultad CDATA #REQUIRED 
cantidadComensales CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingredientes (ingrediente*)>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingredientes cantidadIngredientes CDATA #REQUIRED>
<!ELEMENT proceso (paso*)>
<!ATTLIST proceso pasos CDATA #REQUIRED>
<!ELEMENT paso (#PCDATA)>

=== joseluissdb/mi-proyecto/XML/XML/receta.xml/andres/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cocina SYSTEM "receta.dtd">
<cocina>
    <receta vegano="false" noGluten="false" noLactosa="false" dificultad="media" cantidadComensales="4">
        <ID>1</ID>
        <nombre>Sopa de cebolla</nombre>
        <ingredientes cantidadIngredientes="9">
            <ingrediente>1 Kg. de cebollas.</ingrediente>
                <ingrediente>2 l. de caldo de carne.</ingrediente>
                <ingrediente>100 gr. mantequilla.</ingrediente>
                <ingrediente>1 cucharada de harina.</ingrediente>
                <ingrediente>100 gr. de queso emmental suizo o gruyére rallado.</ingrediente>
                <ingrediente>Pan tostado en rebanadas.</ingrediente>
                <ingrediente>Tomillo.</ingrediente>
                <ingrediente>1 hoja de laurel.</ingrediente>
                <ingrediente>Pimienta.</ingrediente>
        </ingredientes>
        <proceso pasos="6">
            <paso>Pelar y partir las cebollas en rodajas finas.</paso>
            <paso>Rehogarlas con la mantequilla, sal y pimienta a fuego lento hasta que estén transparentes sin dorarse.</paso>
            <paso>Añadir la harina sin dejar de remover.</paso>
            <paso>Ponerlo en una cazuela con el caldo, el tomillo y el laurel.</paso>
            <paso>Dejar cocer a fuego lento durante unos 15 minutos.</paso>
            <paso>Poner las rebanadas de pan encima, espolvorear el queso y gratinar al horno.</paso>
        </proceso>
    </receta>
</cocina>
